[build]
# 依存関係インストール
install = "cd frontend && npm install && cd ../backend && npm install"

# ビルドコマンド
build = "cd frontend && npm run build"

# 起動コマンド（バックエンド側で build 済みのフロントを配信）
start = "cd backend && npm start"
