[build]
commands = [
  "npm run install-all", # frontend と backend の依存をインストール
  "npm run build"        # frontend をビルド
]

[start]
command = "npm run start"

[env]
# 必要な環境変数は Railway ダッシュボードから設定
# DATABASE_URL, DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET, DISCORD_REDIRECT_URI など
