CREATE TABLE IF NOT EXISTS schedules (
  id SERIAL PRIMARY KEY,
  linkid TEXT NOT NULL,
  username TEXT NOT NULL,
  date DATE NOT NULL,
  timeslot TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
  linkid TEXT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT NOW()
);
